name: "Chain Bench action"
description: "Run software supply chain benchmark"
author: Itay Wolfish
branding:
  icon: "zap"
  color: "yellow"
inputs:
  repository-url:
    description: "The github repository url with the server"
    required: true
  github-token:
    description: "Github Token that will be used to access the repository"
    required: true
outputs:
  run-output:
    description: 'JSON output from chain-bench run'
runs:
  using: docker
  image: Dockerfile
  args:
    - 'scan'
    - -r ${{ inputs.repository-url }}
    - -t ${{ inputs.github-token }}
