on: [push]

permissions: read-all

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Chain Bench
        uses: ./
        with:
          command: scan
          args: --repository-url ${{ github.server_url }}/${{ github.repository }} --access-token ${{ secrets.GITHUB_TOKEN }}
